name: Publish Python gitgrind dstribution to PyPI and TestPyPI

on:
  release:
    types: [published]
  pull_request:
    branches:
      - main
    paths:
      - 'gitgrind/**'
      - './pyproject.toml'

jobs:
  build:
    name: Build distribution gitgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install build dependencies
        run: pip install build
      - name: Build sdist and wheel
        run: python -m build
      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  bump-version:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: "0"

      - name: Version bumper
        uses: apowis/pyproject-bump-version@v0.0.1
        with:
          file_to_bump: "./pyproject.toml"
          bump_type: "minor"
          main_branch: "main"
          python_version: "3.10"

  publish-to-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gitgrind # Replace with your actual package name
    permissions:
      id-token: write # Required for trusted publishing
    steps:
      - name: Download all distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
